# Trust all local connections
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# These are for allowing incoming TLS connections
# First is to require mTLS (certificate based passwordless) authentication for any role (user) that has role dbcert_users
hostssl all             +dbcert_users   all                     cert

# Allow TLS connections for all roles
hostssl all             all             all                     scram-sha-256
